name: Hello World
env:
  APP_NAME: "Demo Application"
on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/workflows/*"
  pull_request:
    branches: [main]
  repository_dispatch: 
      types:
        - on-demand-test
jobs:
  echo-vars:
    env:
      PACKAGE_PATH: "."
    runs-on: ubuntu-latest
    steps:
        - name: Echo Github veriable
          env:
            APP_VERSION: "2.3.4"
            RUNNER_CONTEXT: ${{ toJson(runner) }}
          run: |
                echo "This job trigger by ${{github.event_name }}";
                echo "This repository is ${{github.repository }}";
                echo "This branch is ${{github.ref_name }}";
                echo "This  is a ${{env.APP_NAME }} version ${{env.APP_VERSION }}";
                echo "$RUNNER_CONTEXT"
                echo "This DataBase Password is ${{ secrets.DB_PASSWORD }}";
                
  hello-job:
    if: ${{ github.event_name !='on-demand-test'}}
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello GitHub Actions!"
      - name: retrieve client payload
        run: echo "Client send status = ${{github.event.client_payload.status }}"
  Seccond-job:
    if: ${{ github.event_name !='on-demand-test'}}
    runs-on: windows-latest
    needs: hello-job
    steps:
      - name: Run a one-line script
        run: echo "This job is runing on ${{runner.os}}"
        if: ${{ runner.os == 'linux' }}
    
        

  
