on:
    workflow_dispatch:
        inputs:
            environment: 
                description: 'target Environment'
                required: true
                type: choice
                options:
                    - "Staging"
                    - "production"
            run_ui_tests:
                description: 'Run UI testing'
                required: true
                type: boolean
                default: false
                
            
jobs:
    build:
      runs-on: ubunut-latest
      steps:
        - name: Checkout Source code
          uses: actions/checkout@v7.0.0
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
        - name: List files in workspaces
          run: ls ${{ github.workspace }}
    test:
        runs-on: ubuntu-latest
        steps:
        - name: 'UI testing'
          if: ${{ inputs.run_ui_tests }}
          run: echo "run UI testing tools in ${{ inputs.environment }} environment"
